name: "Staticcheck"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run Staticcheck"
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt update && sudo apt install libasound2
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: dominikh/staticcheck-action@v1.0.0
      with:
        version: "2021.1.1"

