name: Staticcheck
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: dominikh/staticcheck-action@v1.0.0
      with:
        version: "2021.1.1"
          make
